name: Prod Deployment
on: [workflow_dispatch]
jobs:
 docker-image-updtaer:
    uses: shehbaz-pathan/Inception-argo-demo/.github/workflows/docker-image-updater.yaml@master
    with:
      env: prod
      destination-file: ./java-sample-application/kustomize-manifest/overlays/stage/kustomization.yaml
 creating-production-pull-request:
   needs: [docker-image-updtaer]
   runs-on: ubuntu-latest
   steps:
     - name: pull-request
       uses: repo-sync/pull-request@v2
       with:
          source_branch: "production-deployment"
          destination_branch: "argocd"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_title: "Production Deployment"
          pr_reviewer: "ruchabhange,shehbaz-pathan"
