name: Stage Deployment
on: [workflow_dispatch]
jobs:
 docker-image-updtaer:
    uses: shehbaz-pathan/Inception-argo-demo/.github/workflows/docker-image-updater.yaml@master
    with:
      destination-file: ./java-sample-application/kustomize-manifest/overlays/stage/kustomization.yaml
 
