name: Stage Deployment
on: [workflow_dispatch]
jobs:
   build:
    name: Deploying image to Stage env
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: 'argocd'
      
    - name: Update Version for productcatalouge image
      run: |
          version=$(cat ./java-sample-application/kustomize-manifest/overlays/stage/kustomization.yaml | grep productcatalouge-image: | awk '{print $2}' | cut -d ':' -f 2 | rev | cut -c2- | rev)
          echo "$version for stage enviornment"
          sed -i "s/$version/${{ github.sha }}/" ./java-sample-application/kustomize-manifest/overlays/stage/kustomization.yaml
          cat ./java-sample-application/kustomize-manifest/overlays/stage/kustomization.yaml | grep productcatalouge-image: | awk '{print $2}' 
    
    - name: Update Version for shopfront image
      run: |
          version=$(cat ./java-sample-application/kustomize-manifest/overlays/stage/kustomization.yaml | grep shopfront-image: | awk '{print $2}' | cut -d ':' -f 2 | rev | cut -c2- | rev)
          echo "$version for stage enviornment"
          sed -i "s/$version/${{ github.sha }}/" ./java-sample-application/kustomize-manifest/overlays/stage/kustomization.yaml
          cat ./java-sample-application/kustomize-manifest/overlays/stage/kustomization.yaml | grep shopfront-image:: | awk '{print $2}' 
    - name: Commit and push changes
      uses: devops-infra/action-commit-push@v0.3
      with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit_message: Image version updated
